# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d67f2fa14fa03987ec98c20969abaedd96e23d622a79c2ea4c6241aa724a22896a741119792ae6b94c7d7788b58ffc88626ca4bf9eee8eeb40a59b58b358d984

test:
  secret_key_base: 8e814e138aae22ea8b3bac3d5d06713310799c1321eea28762938c176e00c86827d9692d6a9ea547c71fbedcf4120d54387cab2265092306009bbf3dbb02552b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
